name: Sync Main to Mirror
on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN_60_DAYS }}
          fetch-depth: 0

      - name: Push to Mirror Repo
        run: |
          git remote add mirror_site https://github.com/sykondroxy/mirror.github.io.git
          git checkout -b mirror-push
          git rm CNAME || echo "No CNAME found"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Remove CNAME for mirror"
          git push --force mirror_site mirror-push:main
