name: Sync Mirror to Main
on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mirror Repo
        uses: actions/checkout@v4
        with:
          # This tells GitHub to use YOUR token for all Git commands below
          token: ${{ secrets.SYNC_TOKEN_60_DAYS }}
          fetch-depth: 0

      - name: Push to Main Site Repo
        run: |
          # Use your real username and main repo name here
          git remote add main_site https://github.com/sykondroxy/androxy.github.io.git
          git push --force main_site main
